{
    'name': 'Premium Tech HR Disciplinary Tracking',
    'version': '18.0.1.0.0',
    'summary': "Employee disciplinary action tracking with configurable categories, approval flow, and HR integration.",
    'description': "Track employee disciplinary actions from initiation through investigation and resolution, with configurable action categories, manager notifications, and HR record linkage.",
    'author': 'Premium Tech',
    'category': 'Human Resources',
    'website': "https://ptech.sh",
    'depends': ['mail', 'hr_payroll', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/disciplinary_sequence.xml',
        'data/demo_data.xml',
        'views/disciplinary_action.xml',
        'views/category_view.xml',
    ],
    # 'demo': ['data/demo_data.xml'],
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
