{ 
    'name': 'MuK REST API for Odoo',
    'summary': 'A customizable RESTful API for Odoo',
    'version': '18.0.1.0.2',
    'category': 'Extra Tools',
    "license": "Other proprietary",
    'price': 195.00,
    'currency': 'EUR',
    'author': 'MuK IT',
    'live_test_url': 'https://mukit.at/#contact',
    'website': 'http://www.mukit.at',
    'contributors': [
        'Mathias Markl <mathias.markl@mukit.at>',
    ],
    'depends': [
        'base_setup',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/menu.xml',
        'views/oauth.xml',
        'views/oauth1.xml',
        'views/oauth2.xml',
        'views/access_rules.xml',
        'views/callback.xml',
        'views/request_data.xml',
        'views/endpoint.xml',
        'views/logging.xml',
        'views/request_token.xml',
        'views/access_token.xml',
        'views/bearer_token.xml',
        'views/authorization_code.xml',
        'views/res_users.xml',
        'views/documentation.xml',
        'views/res_config_settings.xml',
        'template/docs.xml',
        'template/authorize.xml',
    ],
    'demo': [
        'demo/oauth.xml',
        'demo/endpoints.xml',
    ],
    'assets': {
        'web.assets_backend': [
           #'muk_rest/static/src/services/docs_service.js',
           'muk_rest/static/src/webclient/docs_menu/docs_menu.js',
           'muk_rest/static/src/webclient/docs_menu/docs_menu.scss',
           'muk_rest/static/src/webclient/docs_menu/docs_menu.xml',
           'muk_rest/static/src/views/kanban/kanban.scss',
           'muk_rest/static/src/views/icon/icon.scss',
        ],
        'muk_rest.assets_authorize': [
       #     ("include", "web._assets_helpers"),
            'muk_rest/static/src/authorize/authorize.scss',
            'muk_rest/static/src/authorize/authorize.js',
        ],
        'muk_rest.assets_docs': [
            'muk_rest/static/lib/swagger-ui/swagger-ui.css',
            'muk_rest/static/lib/swagger-ui/swagger-ui-bundle.js',
            'muk_rest/static/lib/swagger-ui/swagger-ui-standalone-preset.js',
            'muk_rest/static/src/components/docs/docs.scss',
            'muk_rest/static/src/components/docs/docs.js',
        ],
    },
    'images': [
        'static/description/banner.png'
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
